version: "3.9"
services:
    backend:
        build: "./backend"
        volumes:
            - "./backend/src:/usr/src/app/src"
        ports:
            - "4001:4001"
        env_file:
            - .env
    frontend:
        build: "./frontend"
        volumes:
            - "./frontend/src:/app/src"
            - "./frontend/public:/app/public"
        ports:
            - "4000:3000"
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - 3306:${DATABASE_PORT}
