version: "3.9"
services:
    backend:
        build: "./backend"
        volumes:
            - "./backend/src:/usr/src/app/src"
        ports:
            - "4001:4001"
    frontend:
        build: "./frontend"
        volumes:
            - "./frontend/src:/app/src"
            - "./frontend/public:/app/public"
        ports:
            - "4000:3000"
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
